"use client"

import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import * as z from "zod"
import { Button } from "@/components/ui/button"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { ScheduledMessage } from "./messages-client"
import { toast } from "sonner"
import { useState, useEffect } from "react"
import { Checkbox } from "@/components/ui/checkbox"

const messageFormSchema = z.object({
  recipientId: z.string().min(1, "Recipient is required"),
  recipientName: z.string().min(1, "Recipient name is required"),
  recipientPhone: z.string().min(1, "Phone number is required"),
  caseId: z.string().min(1, "Case is required"),
  docketNumber: z.string().min(1, "Docket number is required"),
  messageType: z.enum(["hearing-reminder", "court-notice", "document-request", "follow-up", "custom"]),
  messageTemplate: z.string(),
  messageBody: z.string().min(10, "Message must be at least 10 characters"),
  scheduledDate: z.string().min(1, "Scheduled date is required"),
  scheduledTime: z.string().min(1, "Scheduled time is required"),
  status: z.enum(["scheduled", "sent", "failed", "cancelled"]),
  autoGenerated: z.boolean(),
  reminderHoursBefore: z.number().optional(),
  notes: z.string().optional(),
})

type MessageFormValues = z.infer<typeof messageFormSchema>

interface MessageFormProps {
  initialData?: ScheduledMessage
  onSubmit: (data: MessageFormValues) => void
  onCancel: () => void
}

const messageTemplates = {
  "hearing-reminder": "Reminder: You have a court hearing for case {docketNumber} on {hearingDate} at {hearingTime}. Please arrive 15 minutes early. Reply STOP to opt out.",
  "court-notice": "Notice: Court hearing for case {docketNumber} has been scheduled for {hearingDate} at {hearingTime} in {courtroom}. Reply STOP to opt out.",
  "document-request": "Action Required: Please bring the following documents to your hearing on {hearingDate}: {documents}. Reply STOP to opt out.",
  "follow-up": "Follow-up: Regarding case {docketNumber}, please contact your case worker at {caseWorkerPhone}. Reply STOP to opt out.",
  "custom": "",
}

export function MessageForm({ initialData, onSubmit, onCancel }: MessageFormProps) {
  const [contacts, setContacts] = useState<Array<{ id: string; firstName: string; lastName: string; phoneNumber: string }>>([])
  const [cases, setCases] = useState<Array<{ id: string; docketNumber: string }>>([])

  useEffect(() => {
    const savedContacts = localStorage.getItem("dhsms_contacts")
    if (savedContacts) {
      const parsedContacts = JSON.parse(savedContacts)
      setContacts(parsedContacts.map((c: any) => ({ 
        id: c.id, 
        firstName: c.firstName, 
        lastName: c.lastName,
        phoneNumber: c.phoneNumber 
      })))
    }

    const savedCases = localStorage.getItem("dhsms_cases")
    if (savedCases) {
      const parsedCases = JSON.parse(savedCases)
      setCases(parsedCases.map((c: any) => ({ id: c.id, docketNumber: c.docketNumber })))
    }
  }, [])

  const form = useForm<MessageFormValues>({
    resolver: zodResolver(messageFormSchema),
    defaultValues: initialData || {
      recipientId: "",
      recipientName: "",
      recipientPhone: "",
      caseId: "",
      docketNumber: "",
      messageType: "hearing-reminder",
      messageTemplate: messageTemplates["hearing-reminder"],
      messageBody: messageTemplates["hearing-reminder"],
      scheduledDate: new Date().toISOString().split('T')[0],
      scheduledTime: "09:00",
      status: "scheduled",
      autoGenerated: true,
      reminderHoursBefore: 24,
      notes: "",
    },
  })

  const watchMessageType = form.watch("messageType")
  const watchRecipientId = form.watch("recipientId")
  const watchCaseId = form.watch("caseId")

  useEffect(() => {
    const template = messageTemplates[watchMessageType]
    if (template) {
      form.setValue("messageTemplate", template)
      form.setValue("messageBody", template)
    }
  }, [watchMessageType, form])

  useEffect(() => {
    const contact = contacts.find(c => c.id === watchRecipientId)
    if (contact) {
      form.setValue("recipientName", `${contact.firstName} ${contact.lastName}`)
      form.setValue("recipientPhone", contact.phoneNumber)
    }
  }, [watchRecipientId, contacts, form])

  useEffect(() => {
    const caseData = cases.find(c => c.id === watchCaseId)
    if (caseData) {
      form.setValue("docketNumber", caseData.docketNumber)
    }
  }, [watchCaseId, cases, form])

  const handleSubmit = (data: MessageFormValues) => {
    onSubmit(data)
    toast.success(initialData ? "Message updated successfully" : "Message scheduled successfully")
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-6">
        <div className="grid gap-6 md:grid-cols-2">
          {/* Recipient */}
          <FormField
            control={form.control}
            name="recipientId"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Recipient</FormLabel>
                <Select onValueChange={field.onChange} defaultValue={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Select recipient" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    {contacts.map((contact) => (
                      <SelectItem key={contact.id} value={contact.id}>
                        {contact.firstName} {contact.lastName} - {contact.phoneNumber}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Case */}
          <FormField
            control={form.control}
            name="caseId"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Case</FormLabel>
                <Select onValueChange={field.onChange} defaultValue={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Select case" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    {cases.map((caseItem) => (
                      <SelectItem key={caseItem.id} value={caseItem.id}>
                        {caseItem.docketNumber}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Message Type */}
          <FormField
            control={form.control}
            name="messageType"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Message Type</FormLabel>
                <Select onValueChange={field.onChange} defaultValue={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Select message type" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    <SelectItem value="hearing-reminder">Hearing Reminder</SelectItem>
                    <SelectItem value="court-notice">Court Notice</SelectItem>
                    <SelectItem value="document-request">Document Request</SelectItem>
                    <SelectItem value="follow-up">Follow-up</SelectItem>
                    <SelectItem value="custom">Custom Message</SelectItem>
                  </SelectContent>
                </Select>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Reminder Hours Before */}
          <FormField
            control={form.control}
            name="reminderHoursBefore"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Send Reminder (Hours Before Hearing)</FormLabel>
                <Select 
                  onValueChange={(value) => field.onChange(parseInt(value))} 
                  defaultValue={field.value?.toString()}
                >
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Select hours" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    <SelectItem value="24">24 hours before</SelectItem>
                    <SelectItem value="48">48 hours before</SelectItem>
                    <SelectItem value="72">72 hours before</SelectItem>
                    <SelectItem value="168">1 week before</SelectItem>
                  </SelectContent>
                </Select>
                <FormDescription>Optional</FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Scheduled Date */}
          <FormField
            control={form.control}
            name="scheduledDate"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Scheduled Date</FormLabel>
                <FormControl>
                  <Input type="date" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Scheduled Time */}
          <FormField
            control={form.control}
            name="scheduledTime"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Scheduled Time</FormLabel>
                <FormControl>
                  <Input type="time" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>

        {/* Message Body */}
        <FormField
          control={form.control}
          name="messageBody"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Message Content</FormLabel>
              <FormControl>
                <Textarea
                  placeholder="Enter your message here..."
                  className="min-h-[150px]"
                  {...field}
                />
              </FormControl>
              <FormDescription>
                Use placeholders: {"{docketNumber}"}, {"{hearingDate}"}, {"{hearingTime}"}, {"{courtroom}"}
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />

        {/* Auto-generated Checkbox */}
        <FormField
          control={form.control}
          name="autoGenerated"
          render={({ field }) => (
            <FormItem className="flex flex-row items-start space-x-3 space-y-0 rounded-md border p-4">
              <FormControl>
                <Checkbox
                  checked={field.value}
                  onCheckedChange={field.onChange}
                />
              </FormControl>
              <div className="space-y-1 leading-none">
                <FormLabel>
                  Auto-generate from template
                </FormLabel>
                <FormDescription>
                  Automatically populate message with case information
                </FormDescription>
              </div>
            </FormItem>
          )}
        />

        {/* Notes */}
        <FormField
          control={form.control}
          name="notes"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Internal Notes</FormLabel>
              <FormControl>
                <Textarea
                  placeholder="Add any internal notes about this message..."
                  className="min-h-[80px]"
                  {...field}
                />
              </FormControl>
              <FormDescription>Optional notes (not sent to recipient)</FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />

        {/* Action Buttons */}
        <div className="flex justify-end gap-4">
          <Button type="button" variant="outline" onClick={onCancel}>
            Cancel
          </Button>
          <Button type="submit">
            {initialData ? "Update Message" : "Schedule Message"}
          </Button>
        </div>
      </form>
    </Form>
  )
}
