"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Plus, MessageSquare, Clock, Send, Search } from 'lucide-react'
import { MessageForm } from "./message-form"
import { MessageList } from "./message-list"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

export interface ScheduledMessage {
  id: string
  recipientId: string
  recipientName: string
  recipientPhone: string
  caseId: string
  docketNumber: string
  messageType: "hearing-reminder" | "court-notice" | "document-request" | "follow-up" | "custom"
  messageTemplate: string
  messageBody: string
  scheduledDate: string
  scheduledTime: string
  status: "scheduled" | "sent" | "failed" | "cancelled"
  sentAt?: string
  deliveryStatus?: "delivered" | "failed" | "pending"
  autoGenerated: boolean
  reminderHoursBefore?: number
  notes?: string
  createdAt: string
  updatedAt: string
}

export function MessagesClient() {
  const [messages, setMessages] = useState<ScheduledMessage[]>([])
  const [showForm, setShowForm] = useState(false)
  const [editingMessage, setEditingMessage] = useState<ScheduledMessage | null>(null)
  const [searchQuery, setSearchQuery] = useState("")
  const [activeTab, setActiveTab] = useState("scheduled")

  // Load messages from localStorage on mount
  useEffect(() => {
    const savedMessages = localStorage.getItem("dhsms_messages")
    if (savedMessages) {
      setMessages(JSON.parse(savedMessages))
    }
  }, [])

  // Save messages to localStorage whenever they change
  useEffect(() => {
    if (messages.length > 0) {
      localStorage.setItem("dhsms_messages", JSON.stringify(messages))
    }
  }, [messages])

  const handleAddMessage = (messageData: Omit<ScheduledMessage, "id" | "createdAt" | "updatedAt">) => {
    const newMessage: ScheduledMessage = {
      ...messageData,
      id: `MSG-${Date.now()}`,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
    setMessages([newMessage, ...messages])
    setShowForm(false)
  }

  const handleEditMessage = (messageData: Omit<ScheduledMessage, "id" | "createdAt" | "updatedAt">) => {
    if (!editingMessage) return
    
    const updatedMessage: ScheduledMessage = {
      ...editingMessage,
      ...messageData,
      updatedAt: new Date().toISOString(),
    }
    
    setMessages(messages.map(m => m.id === editingMessage.id ? updatedMessage : m))
    setEditingMessage(null)
    setShowForm(false)
  }

  const handleDeleteMessage = (id: string) => {
    setMessages(messages.filter(m => m.id !== id))
  }

  const handleCancelMessage = (id: string) => {
    setMessages(messages.map(m => 
      m.id === id ? { ...m, status: "cancelled" as const, updatedAt: new Date().toISOString() } : m
    ))
  }

  const openEditForm = (message: ScheduledMessage) => {
    setEditingMessage(message)
    setShowForm(true)
  }

  const handleCancelForm = () => {
    setShowForm(false)
    setEditingMessage(null)
  }

  const filteredMessages = messages.filter(m => {
    const matchesSearch = m.recipientName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      m.docketNumber.toLowerCase().includes(searchQuery.toLowerCase()) ||
      m.messageBody.toLowerCase().includes(searchQuery.toLowerCase())
    
    const matchesTab = 
      (activeTab === "scheduled" && m.status === "scheduled") ||
      (activeTab === "sent" && m.status === "sent") ||
      (activeTab === "all" && true)
    
    return matchesSearch && matchesTab
  })

  const scheduledCount = messages.filter(m => m.status === "scheduled").length
  const sentCount = messages.filter(m => m.status === "sent").length
  const failedCount = messages.filter(m => m.status === "failed").length
  const todayCount = messages.filter(m => {
    const today = new Date().toISOString().split('T')[0]
    return m.scheduledDate === today && m.status === "scheduled"
  }).length

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-7xl">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold mb-2 text-foreground">Message Scheduling</h1>
          <p className="text-muted-foreground text-lg">
            Schedule automated SMS reminders and notifications for hearings
          </p>
        </div>

        {/* Stats Cards */}
        <div className="grid gap-4 md:grid-cols-4 mb-8">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Scheduled</CardTitle>
              <Clock className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{scheduledCount}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Sent Today</CardTitle>
              <Badge variant="default" className="h-6">Active</Badge>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{todayCount}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Sent</CardTitle>
              <Send className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{sentCount}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Failed</CardTitle>
              <Badge variant="destructive" className="h-6">Error</Badge>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{failedCount}</div>
            </CardContent>
          </Card>
        </div>

        {/* Actions Bar */}
        <div className="flex flex-col sm:flex-row gap-4 mb-6">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              type="text"
              placeholder="Search by recipient, docket number, or message content..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
            />
          </div>
          <Button onClick={() => setShowForm(true)} size="lg">
            <Plus className="mr-2 h-4 w-4" />
            Schedule Message
          </Button>
        </div>

        {/* Form or List */}
        {showForm ? (
          <Card className="mb-8">
            <CardHeader>
              <CardTitle>{editingMessage ? "Edit Scheduled Message" : "Schedule New Message"}</CardTitle>
              <CardDescription>
                {editingMessage 
                  ? "Update message details and scheduling" 
                  : "Create automated SMS reminders for hearings and court dates"}
              </CardDescription>
            </CardHeader>
            <CardContent>
              <MessageForm
                initialData={editingMessage || undefined}
                onSubmit={editingMessage ? handleEditMessage : handleAddMessage}
                onCancel={handleCancelForm}
              />
            </CardContent>
          </Card>
        ) : (
          <Tabs value={activeTab} onValueChange={setActiveTab}>
            <TabsList className="mb-6">
              <TabsTrigger value="scheduled">Scheduled ({scheduledCount})</TabsTrigger>
              <TabsTrigger value="sent">Sent ({sentCount})</TabsTrigger>
              <TabsTrigger value="all">All Messages</TabsTrigger>
            </TabsList>
            <TabsContent value={activeTab}>
              <MessageList
                messages={filteredMessages}
                onEdit={openEditForm}
                onDelete={handleDeleteMessage}
                onCancel={handleCancelMessage}
              />
            </TabsContent>
          </Tabs>
        )}
      </div>
    </div>
  )
}
