"use client"

import { ScheduledMessage } from "./messages-client"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Edit, Trash2, Calendar, Clock, MessageSquare, Phone, XCircle } from 'lucide-react'
import { format } from "date-fns"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"

interface MessageListProps {
  messages: ScheduledMessage[]
  onEdit: (message: ScheduledMessage) => void
  onDelete: (id: string) => void
  onCancel: (id: string) => void
}

const statusColors = {
  scheduled: "default",
  sent: "outline",
  failed: "destructive",
  cancelled: "secondary",
} as const

const messageTypeLabels = {
  "hearing-reminder": "Hearing Reminder",
  "court-notice": "Court Notice",
  "document-request": "Document Request",
  "follow-up": "Follow-up",
  "custom": "Custom",
}

export function MessageList({ messages, onEdit, onDelete, onCancel }: MessageListProps) {
  if (messages.length === 0) {
    return (
      <Card>
        <CardContent className="flex flex-col items-center justify-center py-12">
          <MessageSquare className="h-12 w-12 text-muted-foreground mb-4" />
          <h3 className="text-lg font-semibold mb-2">No messages found</h3>
          <p className="text-muted-foreground text-center">
            Schedule your first automated message reminder
          </p>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="space-y-4">
      {messages.map((message) => (
        <Card key={message.id}>
          <CardHeader>
            <div className="flex items-start justify-between">
              <div className="space-y-1 flex-1">
                <div className="flex items-center gap-2 mb-2">
                  <CardTitle className="text-xl">{message.recipientName}</CardTitle>
                  <Badge variant={statusColors[message.status]}>
                    {message.status.charAt(0).toUpperCase() + message.status.slice(1)}
                  </Badge>
                  <Badge variant="outline">
                    {messageTypeLabels[message.messageType]}
                  </Badge>
                  {message.autoGenerated && (
                    <Badge variant="secondary">Auto</Badge>
                  )}
                </div>
                <CardDescription className="text-base">
                  Case: {message.docketNumber}
                </CardDescription>
              </div>
              <div className="flex gap-2">
                {message.status === "scheduled" && (
                  <>
                    <Button
                      size="icon"
                      variant="outline"
                      onClick={() => onEdit(message)}
                    >
                      <Edit className="h-4 w-4" />
                    </Button>
                    <AlertDialog>
                      <AlertDialogTrigger asChild>
                        <Button size="icon" variant="outline">
                          <XCircle className="h-4 w-4" />
                        </Button>
                      </AlertDialogTrigger>
                      <AlertDialogContent>
                        <AlertDialogHeader>
                          <AlertDialogTitle>Cancel Message?</AlertDialogTitle>
                          <AlertDialogDescription>
                            This will cancel the scheduled message to {message.recipientName}.
                          </AlertDialogDescription>
                        </AlertDialogHeader>
                        <AlertDialogFooter>
                          <AlertDialogCancel>Keep</AlertDialogCancel>
                          <AlertDialogAction onClick={() => onCancel(message.id)}>
                            Cancel Message
                          </AlertDialogAction>
                        </AlertDialogFooter>
                      </AlertDialogContent>
                    </AlertDialog>
                  </>
                )}
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button size="icon" variant="outline">
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>Delete Message?</AlertDialogTitle>
                      <AlertDialogDescription>
                        This will permanently delete this message record. This action cannot be undone.
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>Cancel</AlertDialogCancel>
                      <AlertDialogAction onClick={() => onDelete(message.id)}>
                        Delete
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 mb-4">
              <div className="flex items-center gap-2">
                <Phone className="h-4 w-4 text-muted-foreground" />
                <div>
                  <p className="text-sm font-medium">Phone</p>
                  <p className="text-sm text-muted-foreground">{message.recipientPhone}</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Calendar className="h-4 w-4 text-muted-foreground" />
                <div>
                  <p className="text-sm font-medium">Scheduled Date</p>
                  <p className="text-sm text-muted-foreground">
                    {format(new Date(message.scheduledDate), "MMM dd, yyyy")}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4 text-muted-foreground" />
                <div>
                  <p className="text-sm font-medium">Time</p>
                  <p className="text-sm text-muted-foreground">{message.scheduledTime}</p>
                </div>
              </div>
              {message.reminderHoursBefore && (
                <div className="flex items-center gap-2">
                  <Clock className="h-4 w-4 text-muted-foreground" />
                  <div>
                    <p className="text-sm font-medium">Reminder</p>
                    <p className="text-sm text-muted-foreground">
                      {message.reminderHoursBefore} hours before
                    </p>
                  </div>
                </div>
              )}
              {message.sentAt && (
                <div className="flex items-center gap-2">
                  <Calendar className="h-4 w-4 text-muted-foreground" />
                  <div>
                    <p className="text-sm font-medium">Sent At</p>
                    <p className="text-sm text-muted-foreground">
                      {format(new Date(message.sentAt), "MMM dd, yyyy HH:mm")}
                    </p>
                  </div>
                </div>
              )}
            </div>

            <div className="bg-muted p-4 rounded-md">
              <p className="text-sm font-medium mb-2">Message Content</p>
              <p className="text-sm text-muted-foreground whitespace-pre-wrap">
                {message.messageBody}
              </p>
            </div>

            {message.notes && (
              <div className="mt-4 pt-4 border-t">
                <p className="text-sm font-medium mb-1">Internal Notes</p>
                <p className="text-sm text-muted-foreground">{message.notes}</p>
              </div>
            )}
          </CardContent>
        </Card>
      ))}
    </div>
  )
}
